name: CI/CD UNAL

on:
  push:
    branches: [ main, principal ]
  pull_request:
    branches: [ main, principal ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requisitos.txt

      - name: Train model
        run: python tren.py

      - name: Validate model
        run: python validar.py
